....

diff --git a/machine/decompression_script b/machine/decompression_script
--- a/machine/decompression_script
+++ b/machine/decompression_script
@@ -81,23 +81,16 @@ grep -q github.com $NETRC || {
     chmod 600 $NETRC
 }
 
+# flake 8
+echo "trying to install flake8"
+pip install flake8 --upgrade || echo "Unable to execute pip"
+
 
 echo run vimupdater, which is nexttime started at bashrc
 pkill -9 -f vimupdate || true
 ~/.vimupdate &
 
 chown $(whoami) ~/.vim -R
-
-# TODO let it be precompiled......
-# compile youcompleteme for the platform
-# tern-complete=javascript support, needs nodejs and npm
-cat <<EOF >> ~/.compile-YCM
-#!/bin/bash
-cd ~/.vim/bundle/YouCompleteMe/ && python install.py --tern-complete
-EOF
-chmod a+x ~/.compile-YCM
-#compile YCM
-~/.compile-YCM
 
 echo "Finished"
 exit 0
